Update dirx

diff --git a/dirx b/dirx
--- a/dirx
+++ b/dirx
@@ -3,16 +3,27 @@
 # RAPS production
 # R.C.S.A - DI
 
+clear
+
+# Installations
+if ! command -v apache2 &>/dev/null; then
+    echo "[i] Installing apache2..."
+    if [[ "$(uname -o 2>/dev/null)" == "Android" ]]; then
+        pkg install apache2 -y
+    elif [ "$(uname)" == "Linux" ]; then
+        sudo apt-get update
+        sudo apt-get install -y apache2
+    elif [ "$(uname)" == "Darwin" ]; then
+        brew install apache2
+    else
+        echo "System not supported!"
+        exit 1
+    fi
+fi
 
 clear
-trap 'echo -e "\nOperation aborted by the user."; exit' INT
 
-#Installations
-if [[ "$(uname -o 2>/dev/null)" == "Android" ]]; then
-       pkg install apache2
-else
-       apt-get install apache2
-fi
+trap 'echo -e "\n{>=============================================<}\n                      DONE.\n{>=============================================<}"; exit' INT
 
 clear
 
@@ -26,16 +37,20 @@ function find_directories() {
 
         case $response in
             200)
-                echo "[+] Found: $target_url (+)> 200 [accepted]"
+                echo "[+] Found: /$directory/ (+)> 200 [accepted]"
+                echo " ╘═URL => $target_url "
                 ;;
             403)
-                echo "[+] Forbidden: $target_url (-)> 403"
+                echo "[+] Forbidden: /$directory/ (-)> 403"
+                echo " ╘═URL => $target_url "
                 ;;
             404)
-                echo "[+] Not Found: $target_url (-)> 404"
+                echo "[+] Not Found: /$directory/ (-)> 404"
+                echo " ╘═URL => $target_url "
                 ;;
             *)
-                echo "Unexpected Status Code for $target_url (?)> $response"
+                echo "[-] Unexpected Status Code for /$directory/ (?)> $response"
+                echo " ╘═URL => $target_url "
                 ;;
         esac
     done < "$wordlist_file"
@@ -59,26 +74,33 @@ fi
 
 # Get Apache version and open ports
 apache_version=$(httpd -v | awk -F'[ /]' '/Server version/ {print $4}')
-open_ports=$(netstat -tuln | awk '/^tcp/ {print $4}' | cut -d: -f2 | paste -sd,)
+open_ports=$(netstat -tln | awk '/^tcp/ {print $4}' | awk -F: '{print $NF}' | paste -sd,)
 
+# Extract only the filename from the wordlist path
+wordlist_filename=$(basename "$wordlist_path")
 
-echo
-echo -e "|¯¯¯¯|\¯¯¯\‚|¯¯¯¯¯¯¯¯¯|'|¯¯¯¯|\¯¯¯\’|¯¯¯¯’|/¯¯¯¯/"
-echo -e "|    |'|   ||__/| |\__|‚|    | |   ||__        / "
-echo -e "|    |'|   ||¯¯\| |/¯¯|‚|    |/   /  /       ¯¯| "
-echo -e "|____|/___/‚|_________|'|____|\___\’/____/|____| "
+# User feedback with ASCII art
+echo -e "\n            ####__   ___/ /___                      "
+echo -e "            ######} |** \\ \\  |\\_                    "
+echo -e "             ######}„_@_ //_@_  |<{//////////       "
+echo -e "|¯¯¯¯|\\¯¯¯\\‚|¯¯¯¯¯¯¯¯¯|/|¯¯¯¯|\\¯¯¯\\’|¯¯¯¯’|/¯¯¯¯/"
+echo -e "|    |'|   ||__/| |\\__|‚|    | |   ||__        / "
+echo -e "|    |'|   ||¯¯\\| |/¯¯|‚|    |/   /  /       ¯¯| "
+echo -e "|____|/___/‚|_________|'|____|\\___\\’/____/|____| "
 echo -e "                                        TRABBIT  "
 echo -e "{>=============================================<}"
-echo -e "| [+] TARGET / $target_url {-u}"
-echo -e "| [+] WORDLIST / $wordlist_path {-w}"
-echo -e "| [+] Apache Version: $apache_version"
-echo -e "| [+] Open Ports: $open_ports"
+echo -e "| [+] TARGET => $target_url {-u}                 "
+echo -e "| [+] WORDLIST => $wordlist_filename {-w}       "
+echo -e "| [+] Apache Version => $apache_version          "
+echo -e "| [+] Open Ports => $open_ports                  "
 echo -e "{>=============================================<}"
-echo -e " \\\\\\ DIRECTORIES BRUTEFORCE STARTED \\\\\\"
+echo -e "      \\\\\ DIRECTORIES BRUTEFORCE STARTED \\\\\ "
 echo -e "{>=============================================<}\n"
 
+# Execute directory brute force
 find_directories "$target_url" "$wordlist_path"
 
+# User feedback
 echo -e "{>=============================================<}"
 echo -e "                      DONE.                      "
 echo -e "{>=============================================<}"
